name: 새로 올라온 방 정보 탐색하기
on:
    push:
        branches:
            - master
            - test-actions
    schedule:
        # 12시, 17시 10분
        - cron: '10 1,8 * * *'
jobs:
    fetch:
        name: Fetch
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: 방 정보 탐색하기
              run: |
                  npm ci
                  npm run fetch
              env:
                  MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
                  MONGODB_ID: ${{ secrets.MONGODB_ID }}
                  MONGODB_PW: ${{ secrets.MONGODB_PW }}
                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                  TELEGRAM_DEV_CHAT_ID: ${{ secrets.TELEGRAM_DEV_CHAT_ID }}
                  TELEGRAM_MY_CHAT_ID: ${{ secrets.TELEGRAM_MY_CHAT_ID }}
                  TELEGRAM_Y_CHAT_ID: ${{ secrets.TELEGRAM_Y_CHAT_ID }}
                  TELEGRAM_BIN_CHAT_ID: ${{ secrets.TELEGRAM_BIN_CHAT_ID }}
