name: 새로 올라온 방 정보 탐색하기
on:
    push:
        branches:
            - master
            - test-actions
    schedule:
        # 12시, 17시 (GitHub Action은 UTC 타임존 기준인데 실행 시 1.5시간 딜레이가 있는 듯하여 일정 앞으로 당김)
        - cron: '30 1,6 30 * *'
jobs:
    fetch:
        name: Fetch
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: 방 정보 탐색하기
              run: |
                  npm ci
                  npm run fetch
              env:
                  MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
                  MONGODB_ID: ${{ secrets.MONGODB_ID }}
                  MONGODB_PW: ${{ secrets.MONGODB_PW }}
                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
